### ISSUE TITLE
Broken Pipe exception when running on Heroku

### ISSUE THREAD

**Issue by Jay-ArBrouillard** [Niflheim/Stockfish-Java#7]
2020-10-08T15:36:21.333075+00:00 app[worker.1]: chess.player.ai.stockfish.exception.StockfishInitException: Unable to start and bind Stockfish process:
2020-10-08T15:36:21.333499+00:00 app[worker.1]: at chess.player.ai.stockfish.engine.UCIEngine.<init>(UCIEngine.java:54)
2020-10-08T15:36:21.333614+00:00 app[worker.1]: at chess.player.ai.stockfish.engine.Stockfish.<init>(Stockfish.java:13)
2020-10-08T15:36:21.333733+00:00 app[worker.1]: at chess.player.ai.stockfish.StockFishClient.<init>(StockFishClient.java:16)
2020-10-08T15:36:21.333888+00:00 app[worker.1]: at chess.player.ai.stockfish.StockFishClient$Builder.build(StockFishClient.java:73)
2020-10-08T15:36:21.334024+00:00 app[worker.1]: at Main.main(Main.java:38)
2020-10-08T15:36:21.334350+00:00 app[worker.1]: Caused by: java.io.IOException: Broken pipe
2020-10-08T15:36:21.334452+00:00 app[worker.1]: at java.io.FileOutputStream.writeBytes(Native Method)
2020-10-08T15:36:21.334589+00:00 app[worker.1]: at java.io.FileOutputStream.write(FileOutputStream.java:326)
2020-10-08T15:36:21.334725+00:00 app[worker.1]: at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
2020-10-08T15:36:21.334935+00:00 app[worker.1]: at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
2020-10-08T15:36:21.335075+00:00 app[worker.1]: at java.io.FilterOutputStream.close(FilterOutputStream.java:158)
2020-10-08T15:36:21.335194+00:00 app[worker.1]: at sun.nio.cs.StreamEncoder.implClose(StreamEncoder.java:320)
2020-10-08T15:36:21.335322+00:00 app[worker.1]: at sun.nio.cs.StreamEncoder.close(StreamEncoder.java:149)
2020-10-08T15:36:21.335460+00:00 app[worker.1]: at java.io.OutputStreamWriter.close(OutputStreamWriter.java:233)
2020-10-08T15:36:21.335595+00:00 app[worker.1]: at java.io.BufferedWriter.close(BufferedWriter.java:266)
2020-10-08T15:36:21.335753+00:00 app[worker.1]: at chess.player.ai.stockfish.engine.UCIEngine.<init>(UCIEngine.java:36)

I've trace the error back to output.flush(). This works completely fine in local but when deployed on Heroku throws this error.

**Comment by Jay-ArBrouillard** [comment]
I was using the wrong binary during my Heroku deployment. Closing this issue.
